name: 🧪 Run Unit Tests

on: [push, pull_request]

jobs:
  Tests:
    name: Run All Tests on 3.5.1
    runs-on: ubuntu-latest
    container: barichello/godot-ci:mono-3.5.1
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Update Submodules
        run: git submodule update --init

      - name: Remove Stub Project
        uses: jacobtomlinson/gha-find-replace@v3
        with:
          find: "(\r\n|\r|\n)Project(.*?)\"StubProject\"(.*?)(\r\n|\r|\n)EndProject"
          replace: " "
          regex: true

      - name: Install Dependencies
        run: |
          nuget restore
          mkdir -p .mono/assemblies/Debug
          cp /usr/local/bin/GodotSharp/Api/Release/* .mono/assemblies/Debug

      - name: Compile
        run: msbuild

      - name: Run
        run: godot addons/WAT/cli.tscn run=all

      - name: Upload Test Results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: Test Results
          path: Tests/results.xml
